# Generated by Django 3.1.3 on 2020-11-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201127_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
    ]
